# Default values for zuidui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: zuidui
name: api-gateway-rollout
pathtest: tfm-local/api/health
###############
####ingress####
###############
ingress:
  name: ingress-controller
  host: tfm-local
  pathType: Prefix 
  portFrontend: 8080
  portApiGateway: 8081
###############
##api-gateway##
###############
apiGateway:
  name: api-gateway
  replicaCount: 1
  image:
    repository: zuidui/api-gateway-dev
    tag: 0.0.2
    next_rc: rc11
    
  containerPort: 8081

  service:
    type: ClusterIP
    port: 8081