apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.apiGateway.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.port }}
  type: {{ .Values.apiGateway.service.type }}
