version: '3.9'

services:
  api-gateway:
    container_name: ${IMAGE_NAME}
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT}
        - APP_HOST=${APP_HOST}
        - APP_MODULE=${APP_MODULE}
        - DEBUG_PORT=${DEBUG_PORT}
    volumes:
      - ../app:/workspace/app
      - ../.devcontainer:/workspace/.devcontainer
      - ../.vscode:/workspace/.vscode
    working_dir: /workspace/app/src
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    env_file:
      - .env
    environment:
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
      - APP_MODULE=${APP_MODULE}
      - DEBUG_PORT=${DEBUG_PORT}
    networks:
      - zuidui

networks:
  zuidui:
    name: zuidui
    driver: bridge
