version: '3.9'

services:
  api-gateway:
    container_name: ${IMAGE_NAME}
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT}
        - APP_HOST=${APP_HOST}
        - APP_MODULE=${APP_MODULE}
    volumes:
      - ./src:/app/src
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    environment:
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
      - APP_MODULE=${APP_MODULE}
      - PYTHONPATH=/app/src
    networks:
      - zuidui

networks:
  zuidui:
    driver: bridge