name: CI-PRO

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'app/.dockerignore'
  
jobs:
  integration-tests:
    name: Run integration tests and publish release candidate Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: make build
      - name: Run integration tests
        run: make test-integration      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: Publish the release candidate Docker image
        run: make publish-image-rc          

  publish-image:
    name: Tag and publish the latest Docker image
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}       
      - name: Publish the latest Docker image
        run: make publish-image-latest    